POST http://localhost:3000/donations/
Content-Type: application/json

{
    "donatorName": "Isaque Barbosa Alves",
    "amount": 450,
    "date": "2025-10-04",
    "donatorCpf": "123.456.789-10",
    "donatorPhone": "99999-9999",
    "donatorCep": "12345-678"
}